### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

### ISSUE THREAD

**Issue by hobdell-SAP** [kubernetes/website#12499]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

All interactive tutorials are non-functional.

https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/
* Click "Start Scenario"
* All actions in the tutorial are inactive: 
** There's no way to enter information into the terminal screen: no cursor in the terminal, no prompt; clicking the terminal does nothing; typing the command anyway and hitting enter displays nothing.
** No buttons in the tutorial are active.
** No action links in the tutorial are active.
* Exception in console:
```
* GET https://kubernetes.io/docs/tutorials/kubernetes-basics/public/fonts/RobotoSlab-Regular.woff2 net::ERR_ABORTED 404
* (index):25: GET https://kubernetes.io/docs/tutorials/kubernetes-basics/public/fonts/RobotoSlab-Regular.woff net::ERR_ABORTED 404
* (index):1: GET https://kubernetes.io/docs/tutorials/kubernetes-basics/public/fonts/RobotoSlab-Regular.ttf net::ERR_ABORTED 404
* application.js:1: Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at getCookie (https://katacoda.com/js/application.js:1:131404)
    at TerminalViewLayout.init (https://katacoda.com/javascripts/terminal-application.js:1:1067)
    at window.on_page_load (https://katacoda.com/embed/kubernetes-bootcamp/7/?embed=true&ui=inline&host=kubernetes.io&url=https%3A%2F%2Fkubernetes.io%2Fdocs%2Ftutorials%2Fkubernetes-basics%2Fdeploy-app%2Fdeploy-interactive%2F&target=inline-terminal-1&prompt=Kubernetes%20Bootcamp%20Terminal&color=326de6&secondary=273d6d&hideintro=false&font=Roboto&fontheader=Roboto%20Slab:280:17)
    at App.init (https://katacoda.com/js/application.js:1:133133)
<snip>
```

Using: 
* Chrome Version 71.0.3578.98 (Official Build) (64-bit)
* Mojave on MBP

**Proposed Solution:**
Possibly related to https://github.com/GoogleChrome/puppeteer/issues/1607 - attempting to get the localStorage before the page is loaded? I am not an Expert.

**Page to Update:**
* ALL Interactive Tutorials under https://kubernetes.io/docs/tutorials/

**Comment by hobdell-SAP** [comment]
Tested today - confirmed as fixed on the v1.14 interactive tutorial.
