### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/dual-stack/

### ISSUE THREAD

**Issue by jeremyxu2010** [kubernetes/website#16801]
I do as it, but failed.

参考[kubernetes IPv4/IPv6双栈的官方文档](https://kubernetes.io/docs/concepts/services-networking/dual-stack/)，实施IPv4/IPv6双栈的步骤。虽然是严格按官方文档实施的，但最终遇到报错，没能成功。这里记录一下。

ipv6地址规划：

| 地址范围                 | 值             |      |
| ------------------------ | -------------- | ---- |
| pod-cluster-cidr         | fc00:0f00::/24  |      |
| service-cluster-ip-range | fc00:1f00::/24  |      |
| docker fixed-cidr-v6     | fc00:2f00::/24 |      |

## 停止服务

```bash
$ systemctl stop kubelet
$ docker ps -q | xargs docker stop
$ systemctl stop docker
```

## docker启用IPv6支持

```bash
# 编辑docker的daemon.json，增加ipv6等选项
$ vim /etc/docker/daemon.json
......
  "ipv6": true,
  "fixed-cidr-v6": "fc00:2f00::/24",
......

# 编辑/etc/sysctl.d/11-ipv6-forwarding.conf，开启一些内核选项，其中enp1s0为物理网口的名称
$ vim /etc/sysctl.d/11-ipv6-forwarding.conf
net.ipv6.conf.default.forwarding=1
net.ipv6.conf.all.forwarding=1
net.ipv6.conf.enp1s0.accept_ra=2

# 应用sysctl配置
$ sysctl --system -p

# 启动docker服务
$ systemctl start docker
```

## 升级kubernetes至1.16版本

```bash
# 升级kubelet
$ curl -O -L https://dl.k8s.io/v1.16.1/kubernetes-node-linux-arm64.tar.gz
$ tar -xf kubernetes-node-linux-arm64.tar.gz
$ cp -f kubernetes/node/bin/kubelet /usr/bin/kubelet

# 升级kube-apiserver镜像
$ docker pull gcr.io/google-containers/kube-apiserver:v1.16.1
$ docker tag gcr.io/google-containers/kube-apiserver:v1.16.1 tke3.global.registry.tcnp.china.com/tke3/kube-apiserver:v1.16.1
$ sed -i -e 's/image:.*/image: tke3.global.registry.tcnp.china.com\/tke3\/kube-apiserver:v1.16.1/' /etc/kubernetes/manifests/kube-apiserver.yaml

# 升级kube-controller-manager镜像
$ docker pull gcr.io/google-containers/kube-controller-manager:v1.16.1
$ docker tag gcr.io/google-containers/kube-controller-manager:v1.16.1 tke3.global.registry.tcnp.china.com/tke3/kube-controller-manager:v1.16.1
$ sed -i -e 's/image:.*/image: tke3.global.registry.tcnp.china.com\/tke3\/kube-controller-manager:v1.16.1/' /etc/kubernetes/manifests/kube-controller-manager.yaml

# 升级kube-scheduler镜像
$ docker pull gcr.io/google-containers/kube-scheduler:v1.16.1
$ docker tag gcr.io/google-containers/kube-scheduler:v1.16.1 tke3.global.registry.tcnp.china.com/tke3/kube-scheduler:v1.16.1
$ sed -i -e 's/image:.*/image: tke3.global.registry.tcnp.china.com\/tke3\/kube-scheduler:v1.16.1/' /etc/kubernetes/manifests/kube-scheduler.yaml

# 预先拉取v1.16.1版本的kube-proxy镜像
$ docker pull gcr.io/google-containers/kube-proxy:v1.16.1
$ docker tag gcr.io/google-containers/kube-proxy:v1.16.1 tke3.global.registry.tcnp.china.com/tke3/kube-proxy:v1.16.1

# 更新kubectl
$ curl -O -L https://dl.k8s.io/v1.16.1/kubernetes-client-linux-arm64.tar.gz
$ tar -xf kubernetes-client-linux-arm64.tar.gz
$ cp -f kubernetes/client/bin/kubectl /usr/bin/kubectl
```

## 修改关键组件配置选项

```bash
# 编辑kubelet的配置文件，开启IPv6DualStack的feature-gate, 切换为使用kubenet的network plugin
$ vim /etc/sysconfig/kubelet
KUBELET_EXTRA_ARGS=--feature-gates="IPv6DualStack=true" --network-plugin=kubenet

# 编辑kube-controller-manager的部署yaml文件，修改--feature-gates、--cluster-cidr、--service-cluster-ip-range选项
$ vim /etc/kubernetes/manifests/kube-controller-manager.yaml
......
spec:
  containers:
  - command:
    - kube-controller-manager
    - --allocate-node-cidrs=true
    - --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --bind-address=127.0.0.1
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --cluster-cidr=172.20.0.0/16,fc00:0f00::/24
    - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
    - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
    - --controllers=*,bootstrapsigner,tokencleaner
    - --kubeconfig=/etc/kubernetes/controller-manager.conf
    - --leader-elect=true
    - --node-cidr-mask-size=24
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --root-ca-file=/etc/kubernetes/pki/ca.crt
    - --service-account-private-key-file=/etc/kubernetes/pki/sa.key
    - --service-cluster-ip-range=172.20.255.0/24,fc00:1f00::/24
    - --use-service-account-credentials=true
    - --feature-gates=IPv6DualStack=true
......
```

## 宿主机上安装ipvs

```bash
# 宿主机安装ipvs相关软件
$ apt-get install -y ipset ipvsadm
# 加载ipvs相关内核模块
$ modprobe -- ip_vs
$ modprobe -- ip_vs_rr
$ modprobe -- ip_vs_wrr
$ modprobe -- ip_vs_sh
$ modprobe -- nf_conntrack_ipv4
```

## 修改kube-proxy配置选项

```bash
# 启动kubelet，它会自动拉起kubernetes的控制面pod，随后会拉起在kubernetes中声明的部署组件
$ systemctl start kubelet

# 修改kube-proxy的镜像为v1.16.1版本的kube-proxy
$ kubectl -n kube-system edit daemonsets kube-proxy
......
image: tke3.global.registry.tcnp.china.com/tke3/kube-proxy:v1.16.1
......

# 修改kube-proxy的配置选项，修改了featureGates、clusterCIDR、mode选项
$ kubectl -n kube-system edit configmaps kube-proxy
apiVersion: v1
data:
  config.conf: |-
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    ......
    featureGates:
      IPv6DualStack: true
    clusterCIDR: "172.20.0.0/16,fc00:0f00::/24"
    mode: "ipvs"
    ......
```

## 检查部署信息

至此，所有官方文档上说明的动作已严格执行，但检查kubernetes中的pod，发现kube-proxy的pod未能正常运行，报错信息也不明朗，无从查错，尝试过多种办法，均无法解决下面的问题。

```bash
$ root@Kylin:~/dist# kubectl get pod --all-namespaces
NAMESPACE       NAME                                        READY   STATUS             RESTARTS   AGE
ceph            cephfs-provisioner-7d4dcc78df-nshjd         1/1     Running            1          4h1m
ceph            rbd-provisioner-779577fc58-6sftd            1/1     Running            1          4h1m
ingress-nginx   nginx-ingress-controller-776bd54d68-sqxzl   1/1     Running            1          4h1m
kube-system     coredns-69b654f497-drbdk                    1/1     Running            1          4h1m
kube-system     coredns-69b654f497-vkvmb                    1/1     Running            1          4h1m
kube-system     etcd-192.168.122.82                         1/1     Running            0          126m
kube-system     flannel-8hv72                               1/1     Running            0          69m
kube-system     fluentd-elasticsearch-z4q42                 1/1     Running            1          4h1m
kube-system     galaxy-daemonset-djp4q                      1/1     Running            1          4h1m
kube-system     heapster-797458cc65-4jq89                   1/1     Running            0          74m
kube-system     kube-apiserver-192.168.122.82               1/1     Running            0          126m
kube-system     kube-controller-manager-192.168.122.82      1/1     Running            0          122m
kube-system     kube-proxy-vmb5l                            0/1     CrashLoopBackOff   13         44m
kube-system     kube-scheduler-192.168.122.82               1/1     Running            0          126m
kube-system     kube-state-metrics-65d9474496-rswd5         1/1     Running            1          4h1m
kube-system     prometheus-node-exporter-bn69m              1/1     Running            1          4h1m
kube-system     swift-7f45754788-wwn92                      2/2     Running            2          3h58m
kube-system     tiller-deploy-8776ddcbb-n6h95               1/1     Running            1          3h58m
tcnp            cluster-console-bf5b97bbd-t9p7h             1/1     Running            1          4h1m

$ kubectl -n kube-system logs kube-proxy-vmb5l
I1010 09:46:12.668939       1 node.go:135] Successfully retrieved node IP: 192.168.122.82
I1010 09:46:12.669012       1 server_others.go:176] Using ipvs Proxier.
I1010 09:46:12.669024       1 server_others.go:178] creating dualStackProxier for ipvs.
W1010 09:46:12.671672       1 proxier.go:420] IPVS scheduler not specified, use rr by default
W1010 09:46:12.671997       1 proxier.go:420] IPVS scheduler not specified, use rr by default
W1010 09:46:12.672040       1 ipset.go:116] ipset name truncated; [KUBE-6-LOAD-BALANCER-SOURCE-CIDR] -> [KUBE-6-LOAD-BALANCER-SOURCE-CID]
W1010 09:46:12.672066       1 ipset.go:116] ipset name truncated; [KUBE-6-NODE-PORT-LOCAL-SCTP-HASH] -> [KUBE-6-NODE-PORT-LOCAL-SCTP-HAS]
I1010 09:46:12.672379       1 server.go:529] Version: v1.16.1
I1010 09:46:12.673286       1 conntrack.go:52] Setting nf_conntrack_max to 524288
I1010 09:46:12.673891       1 config.go:313] Starting service config controller
I1010 09:46:12.673965       1 shared_informer.go:197] Waiting for caches to sync for service config
I1010 09:46:12.673855       1 config.go:131] Starting endpoints config controller
I1010 09:46:12.673997       1 shared_informer.go:197] Waiting for caches to sync for endpoints config
E1010 09:46:12.676058       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 85 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x10f0220, 0x251d3f0)
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x84
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x7c
panic(0x10f0220, 0x251d3f0)
	/usr/local/go/src/runtime/panic.go:522 +0x1a0
k8s.io/kubernetes/pkg/proxy/ipvs.(*metaProxier).OnServiceAdd(0x4000536020, 0x400062f000)
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/ipvs/meta_proxier.go:61 +0x28
k8s.io/kubernetes/pkg/proxy/config.(*ServiceConfig).handleAddService(0x40007800e0, 0x12c1da0, 0x400062f000)
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/config/config.go:333 +0x74
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:198
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x40007a1df8, 0x3c280, 0x40007a1db8)
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:658 +0x240
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0x4000600e18, 0x40007a1e28, 0x2dc69c)
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292 +0x50
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:652 +0x78
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0x40007a1f50)
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x50
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x4000600f50, 0xdf8475800, 0x0, 0x1, 0x40001f60c0)
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xb8
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0x4000796000)
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:650 +0x88
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0x40001801b0, 0x400053a130)
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x54
created by k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x5c
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xf2cae8]

goroutine 85 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x104
panic(0x10f0220, 0x251d3f0)
	/usr/local/go/src/runtime/panic.go:522 +0x1a0
k8s.io/kubernetes/pkg/proxy/ipvs.(*metaProxier).OnServiceAdd(0x4000536020, 0x400062f000)
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/ipvs/meta_proxier.go:61 +0x28
k8s.io/kubernetes/pkg/proxy/config.(*ServiceConfig).handleAddService(0x40007800e0, 0x12c1da0, 0x400062f000)
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/config/config.go:333 +0x74
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:198
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x40007a1df8, 0x3c280, 0x40007a1db8)
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:658 +0x240
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0x4000600e18, 0x40007a1e28, 0x2dc69c)
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292 +0x50
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:652 +0x78
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0x40007a1f50)
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x50
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x4000600f50, 0xdf8475800, 0x0, 0x1, 0x40001f60c0)
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xb8
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0x4000796000)
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:650 +0x88
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0x40001801b0, 0x400053a130)
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x54
created by k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x5c
```

检查了很久，未能发现原因。。。

另外按[官方IPv4/IPv6双栈的检验文档](https://kubernetes.io/docs/tasks/network/validate-dual-stack/)，发现双栈未能生效，原因不明。

```bash
# 仅输出了IPv4的地址
$ kubectl get nodes 192.168.122.82 -o go-template --template='{{range .spec.podCIDRs}}{{printf "%s\n" .}}{{end}}'
172.20.0.0/24

# 仅输出了IPv4的地址
$ kubectl get nodes 192.168.122.82 -o go-template --template='{{range .status.addresses}}{{printf "%s: %s \n" .type .address}}{{end}}'
InternalIP: 192.168.122.82
Hostname: 192.168.122.82

# 仅输出了IPv4的地址
$ kubectl -n kube-system get pods tiller-deploy-8776ddcbb-n6h95 -o go-template --template='{{range .status.podIPs}}{{printf "%s \n" .ip}}{{end}}'
172.20.0.10
```

**Comment by brianmay** [comment]
English translation: https://translate.google.com/translate?hl=en&sl=zh-CN&u=https://github.com/kubernetes/website/issues/16801&prev=search

**Comment by timyl** [comment]
@jeremyxu2010 is there any updates on this issue ? I met the same issue with kube-proxy in k8sv1.18.3...

**Comment by Duanzhiwei** [comment]
is there any updates on this issue ? I met the same issue  in k8sv1.18.2

**Comment by howieyuen** [comment]
I have met the same problem，but I checked the panic a little bit，might be some service object doesn't have `ipFamily` field，kube-proxy did not adapt for these svc resources，so I deleted them handly，and running successfully  

> is there any updates on this issue ? I met the same issue in k8sv1.18.2

**Comment by Duanzhiwei** [comment]
> I have met the similar panic in k8s v1.18.1，after reviewing the panic code a little bit，it might be caused by some svc objects which don't have `ipFamily` field，for some reason I don't know，kube-proxy did not add it for them automatically，so I deleted them by hand，and then kube-proxy is running smoothly.
> 
> > is there any updates on this issue ? I met the same issue in k8sv1.18.2

The components of my cluster are running normally, but I cannot get the IPv6 address of the node. Pod can be assigned to two addresses: ipv4 and ipv6，but cannot be accessed with ipv6。

**Comment by brianmay** [comment]
According to https://kubernetes.io/docs/concepts/services-networking/dual-stack/#services `ipFamily` is suppose to be optional. Is that not correct?

**Comment by brianmay** [comment]
Looks like this is now working with v1.19.4

Curiously though hosts outside the cluster cannot see the IPv6 address that I assigned to a service. As in that address gets assigned to the kube-ipvs0 but Linux isn't responding to this IP address for incoming packets from the ethernet device. Which I find somewhat puzzling as it works fine for IPv4. If I manually assign the IPv6 address to the Ethernet port, then it works fine.
