### ISSUE TITLE
Issue with k8s.io/ko/docs/tutorials/stateful-application/zookeeper/

### ISSUE THREAD

**Issue by wiv33** [kubernetes/website#21715]
**This is a Bug Report**

**Problem:**
This error occurs when you run this yaml file.
I didn't even find the image of zookeeper.
help me. 
---

kubectl apply -f https://k8s.io/examples/application/zookeeper/zookeeper.yaml

2020-06-13 16:17:16,249 [myid:1] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /127.0.0.1:35606                                                                                2020-06-13 16:17:16,250 [myid:1] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@883] - Processing ruok command from /127.0.0.1:35606                                                                                          2020-06-13 16:17:16,252 [myid:1] - INFO  [Thread-66:NIOServerCnxn@1044] - Closed socket connection for client /127.0.0.1:35606 (no session established for client) 
---

**Proposed Solution:**
sorry. I couldn't find a solution because of my short knowledge.

**Page to Update:**
https://kubernetes.io/...

**Comment by wiv33** [comment]
Sorry. I didn't add an error message. I'll post an error message.

2020-06-16 04:08:48,898 [myid:1] - WARN  [QuorumPeer[myid=1]/0.0.0.0:2181:QuorumPeer$QuorumServer@173] - Failed to resolve address: zk-2.zk-hs.default.svc.cluster.local
java.net.UnknownHostException: zk-2.zk-hs.default.svc.cluster.local: Name or service not known
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
        at java.net.InetAddress.getAllByName(InetAddress.java:1192)
        at java.net.InetAddress.getAllByName(InetAddress.java:1126)
        at java.net.InetAddress.getByName(InetAddress.java:1076)
        at org.apache.zookeeper.server.quorum.QuorumPeer$QuorumServer.recreateSocketAddresses(QuorumPeer.java:166)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:595)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectAll(QuorumCnxManager.java:614)
        at org.apache.zookeeper.server.quorum.FastLeaderElection.lookForLeader(FastLeaderElection.java:843)
        at org.apache.zookeeper.server.quorum.QuorumPeer.run(QuorumPeer.java:913)

**Comment by davehouser1** [comment]
Can we reopen this. This is still a issue.
zookeeper will not resolve DNS properly following the sites instructions. 
This link states that zookeeper starts listening on 127.0.0.1 and causes the resolution problem. Can you confirm?
No requirements are given on the site re: OS version, kernel version, docker version, etc. Currently running ubuntu 18.04 and getting this problem. 

https://stackoverflow.com/questions/46605686/zookeeper-hostname-resolution-fails
