### ISSUE TITLE
Can't preview website with Hugo on Mac: too many files

### ISSUE THREAD

**Issue by craigbox** [kubernetes/website#33278]
I am running Hugo, built with homebrew, on an intel Mac running macOS 12.3.1.

Trying to run `hugo serve` gives this output:

```
craigbox@craigbox-macbookpro1:~/Documents/Projects/kubernetes.github.io $ make serve
hugo server --buildFuture --environment development
Start building sites … 
hugo v0.97.3+extended darwin/amd64 BuildDate=unknown
(warnings trimmed)


                   |  EN  |  ZH  | KO  | JA  | FR  | IT  | DE  | ES  | PT-BR | ID  | RU  | VI  | PL  | UK   
-------------------+------+------+-----+-----+-----+-----+-----+-----+-------+-----+-----+-----+-----+------
  Pages            | 1440 | 1012 | 539 | 450 | 338 |  71 | 164 | 292 |   185 | 335 | 155 |  77 |  69 |  92  
  Paginator pages  |   42 |    9 |   0 |   0 |   0 |   0 |   0 |   0 |     0 |   0 |   0 |   0 |   0 |   0  
  Non-page files   |  507 |  382 | 200 | 266 |  73 |  20 |  17 |  33 |    30 | 105 |  24 |   8 |   6 |  20  
  Static files     |  834 |  834 | 834 | 834 | 834 | 834 | 834 | 834 |   834 | 834 | 834 | 834 | 834 | 834  
  Processed images |    1 |    1 |   0 |   0 |   0 |   0 |   0 |   0 |     0 |   0 |   0 |   0 |   0 |   0  
  Aliases          |    8 |    2 |   3 |   1 |   0 |   1 |   0 |   0 |     1 |   1 |   1 |   0 |   0 |   0  
  Sitemaps         |    2 |    1 |   1 |   1 |   1 |   1 |   1 |   1 |     1 |   1 |   1 |   1 |   1 |   1  
  Cleaned          |    0 |    0 |   0 |   0 |   0 |   0 |   0 |   0 |     0 |   0 |   0 |   0 |   0 |   0  

Built in 19683 ms
Watching for changes in /Users/craigbox/Documents/Projects/kubernetes.github.io/{archetypes,assets,content,data,i18n,layouts,package.json,postcss.config.js,static,themes}
Watching for config changes in /Users/craigbox/Documents/Projects/kubernetes.github.io/config.toml, /Users/craigbox/Documents/Projects/kubernetes.github.io/themes/docsy/config.toml, /Users/craigbox/Documents/Projects/kubernetes.github.io/go.mod
fatal error: pipe failed

goroutine 1 [running]:
runtime.throw({0x5e09d3c?, 0xc000700480?})
	runtime/panic.go:992 +0x71 fp=0xc0d5e21808 sp=0xc0d5e217d8 pc=0x4036ed1
runtime.sigNoteSetup(0xc0d5e21868)
	runtime/os_darwin.go:101 +0xc5 fp=0xc0d5e21830 sp=0xc0d5e21808 pc=0x4033fa5
os/signal.signal_enable(0x2)
	runtime/sigqueue.go:202 +0x39 fp=0xc0d5e21850 sp=0xc0d5e21830 pc=0x40662d9
os/signal.enableSignal(...)
	os/signal/signal_unix.go:49
os/signal.Notify.func1(0x5b88500?)
	os/signal/signal.go:145 +0x73 fp=0xc0d5e21878 sp=0xc0d5e21850 pc=0x57bda93
os/signal.Notify(0xc0b0b009c0, {0xc0d5e21b20, 0x2, 0x5f3b897?})
	os/signal/signal.go:165 +0x1ff fp=0xc0d5e218f0 sp=0xc0d5e21878 pc=0x57bd95f
github.com/gohugoio/hugo/commands.(*commandeer).serve(0xc00056a400, 0xc0003eb000)
	github.com/gohugoio/hugo/commands/server.go:527 +0x47a fp=0xc0d5e21b78 sp=0xc0d5e218f0 pc=0x57f1a3a
github.com/gohugoio/hugo/commands.(*serverCmd).server(0xc0003eb000, 0xc0002f6c80, {0xc000118500?, 0x44da480?, 0xc00093fd00?})
	github.com/gohugoio/hugo/commands/server.go:297 +0x43c fp=0xc0d5e21cd8 sp=0xc0d5e21b78 pc=0x57ee33c
github.com/gohugoio/hugo/commands.(*commandsBuilder).newServerCmdSignaled.func1(0xc0002f6c80?, {0xc000590030?, 0x3?, 0x3?})
	github.com/gohugoio/hugo/commands/server.go:95 +0x36 fp=0xc0d5e21d28 sp=0xc0d5e21cd8 pc=0x57edd96
github.com/spf13/cobra.(*Command).execute(0xc0002f6c80, {0xc000711fb0, 0x3, 0x3})
	github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c fp=0xc0d5e21e00 sp=0xc0d5e21d28 pc=0x44d9a5c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000308500)
	github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4 fp=0xc0d5e21eb8 sp=0xc0d5e21e00 pc=0x44da0d4
github.com/gohugoio/hugo/commands.Execute({0xc00003c0b0, 0x4, 0x4})
	github.com/gohugoio/hugo/commands/hugo.go:93 +0xb4 fp=0xc0d5e21f38 sp=0xc0d5e21eb8 pc=0x57da674
main.main()
	github.com/gohugoio/hugo/main.go:23 +0x57 fp=0xc0d5e21f80 sp=0xc0d5e21f38 pc=0x57f7137
runtime.main()
	runtime/proc.go:250 +0x212 fp=0xc0d5e21fe0 sp=0xc0d5e21f80 pc=0x40395b2
runtime.goexit()
	runtime/asm_amd64.s:1571 +0x1 fp=0xc0d5e21fe8 sp=0xc0d5e21fe0 pc=0x406a381

goroutine 9 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0001ba180)
	go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0xad
created by go.opencensus.io/stats/view.init.0
	go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x8d

goroutine 7356 [select]:
github.com/gohugoio/hugo/watcher.(*Batcher).run(0xc0af24f4a0)
	github.com/gohugoio/hugo/watcher/batcher.go:67 +0x11a
created by github.com/gohugoio/hugo/watcher.New
	github.com/gohugoio/hugo/watcher/batcher.go:56 +0x1ed

goroutine 7355 [syscall]:
syscall.syscall6(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/sys_darwin.go:44 +0x6a
golang.org/x/sys/unix.kevent(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	golang.org/x/sys@v0.0.0-20220209214540-3681064d5158/unix/zsyscall_darwin_amd64.go:276 +0x52
golang.org/x/sys/unix.Kevent(0x5b92ca0?, {0x0?, 0x15?, 0xc000b8092e?}, {0xc0a31a0678?, 0x4008d25?, 0xc019e61500?}, 0x16?)
	golang.org/x/sys@v0.0.0-20220209214540-3681064d5158/unix/syscall_bsd.go:417 +0x3c
github.com/fsnotify/fsnotify.read(0xc00e0f06f0?, {0xc0a31a0678?, 0xc000b8095b?, 0xa}, 0x5aeaac0?)
	github.com/fsnotify/fsnotify@v1.5.1/kqueue.go:512 +0x3f
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc0af466de0)
	github.com/fsnotify/fsnotify@v1.5.1/kqueue.go:275 +0xa5
created by github.com/fsnotify/fsnotify.NewWatcher
	github.com/fsnotify/fsnotify@v1.5.1/kqueue.go:63 +0x1c5

goroutine 7357 [select]:
github.com/gohugoio/hugo/commands.(*commandeer).newWatcher.func1()
	github.com/gohugoio/hugo/commands/hugo.go:875 +0xf9
created by github.com/gohugoio/hugo/commands.(*commandeer).newWatcher
	github.com/gohugoio/hugo/commands/hugo.go:873 +0x38d

goroutine 7144 [select]:
github.com/gohugoio/hugo/livereload.(*hub).run(0x73df5a0)
	github.com/gohugoio/hugo/livereload/hub.go:39 +0xec
created by github.com/gohugoio/hugo/livereload.Initialize
	github.com/gohugoio/hugo/livereload/livereload.go:99 +0x3f
make: *** [serve] Error 2
```

Running with `--watch=false` mitigates the crash.  This is tracked at https://github.com/gohugoio/hugo/issues/8594 and discussed [on the Hugo discourse](https://discourse.gohugo.io/t/hugo-is-crashing-upon-start-of-hugo-server-d-when-serving-a-lot-of-images/28540)

There are also suggestions to [increase the number of files](https://discourse.gohugo.io/t/on-upgrade-to-v0-76-5-fatal-error-pipe-failed/28912/6).

This issue is here to provide the workaround to anyone searching, and to prompt other solutions, like potentially reducing the number of files in the repo to bring it below the problem line.

**Comment by sftim** [comment]
Try this instead:
`make container-image && make container-serve`

That also gets you the recommended Hugo version automagically.

AIUI, we're promoting the container option as the primary way for local development. We like containers&hellip;

**Comment by sftim** [comment]
> reducing the number of files in the repo to bring it below the problem line.

We're actually aiming to localize more of the docs, taking the number of open files much _higher_. The CJK localizations are in the lead at the moment but there's no reason that other localizations couldn't catch up.

**Comment by sftim** [comment]
As a feature enhancement, we could document `--watch=false` as a workaround for people not using a container-based local preview.

**Comment by craigbox** [comment]
Googlers are discouraged* from running VMs on their Macs; the suggested approach generally works, but can be slow as molasses.

(I always forget to build the image; is there a reason everyone has to build it locally rather than one being maintained in a registry?)

**Comment by sftim** [comment]
> is there a reason everyone has to build it locally rather than one being maintained in a registry?

That's a feature request as yet unfiled, @craigbox. Please do feel free!

**Comment by craigbox** [comment]
```
$ hugo serve
Start building sites … 
hugo v0.111.3+extended darwin/arm64 BuildDate=unknown

                   |  EN  | ZH-CN | KO  | JA  | FR  | IT  | DE  | ES  | PT-BR | ID  | HI  | VI  | RU  | PL  | UK   
-------------------+------+-------+-----+-----+-----+-----+-----+-----+-------+-----+-----+-----+-----+-----+------
  Pages            | 1558 |  1162 | 603 | 470 | 340 |  78 | 163 | 297 |   329 | 335 | 110 |  77 | 177 |  68 |  86  
  Paginator pages  |   49 |    14 |   0 |   0 |   0 |   0 |   0 |   0 |     0 |   0 |   0 |   0 |   0 |   0 |   0  
  Non-page files   |  553 |   419 | 226 | 269 |  85 |  20 |  17 |  39 |    45 | 105 |   8 |   8 |  30 |   6 |  19  
  Static files     |  817 |   817 | 817 | 817 | 817 | 817 | 817 | 817 |   817 | 817 | 817 | 817 | 817 | 817 | 817  
  Processed images |    1 |     1 |   0 |   0 |   0 |   0 |   0 |   0 |     0 |   0 |   0 |   0 |   0 |   0 |   0  
  Aliases          |    8 |     6 |   3 |   3 |   0 |   1 |   1 |   0 |     3 |   1 |   0 |   0 |   1 |   0 |   0  
  Sitemaps         |    2 |     1 |   1 |   1 |   1 |   1 |   1 |   1 |     1 |   1 |   1 |   1 |   1 |   1 |   1  
  Cleaned          |    0 |     0 |   0 |   0 |   0 |   0 |   0 |   0 |     0 |   0 |   0 |   0 |   0 |   0 |   0  

Built in 10344 ms
Watching for changes in /Users/craigbox/Documents/Projects/kubernetes.io/{archetypes,assets,content,data,i18n,layouts,package.json,postcss.config.js,static,themes}
Watching for config changes in /Users/craigbox/Documents/Projects/kubernetes.io/hugo.toml, /Users/craigbox/Documents/Projects/kubernetes.io/themes/docsy/config.toml, /Users/craigbox/Documents/Projects/kubernetes.io/go.mod
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

Works well enough for me now!

/close
